#LOCAL
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    version: V0.01
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
    database: h2
  # spring boot 에서 yml 설정 시 mongoDB 자동 등록
  data:
    mongodb:
      uri: mongodb+srv://admin:1234@cluster0.svzdu.mongodb.net
      database: myFirstDatabase

springdoc:
  version: ${spring.application.version}
  app-url: http://localhost:${server.port}
  app-description: Default Skeleton URL
  app-title: SellerMill Skeleton API

  api-docs:
    groups:
      enabled: true
    # springdoc-openapi ????? ???
    enabled: true
    # /api-docs endpoint custom path
    path: /v3/api-docs
  swagger-ui:
    # Swagger-UI ???
    enabled: true
    # swagger-ui custom path
    #    path: /swagger-ui.html
    # ?? PetStore Swagger ????
    disable-swagger-default-url: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    tagsSorter: alpha
    display-query-params-without-oauth2: true